services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./vaultgo_project:/app/vaultgo_project
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
volumes:
  postgres_data:
